/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.cvqc.controller; import cn.zhuatech.cvqc.ai.AiProvider; import cn.zhuatech.cvqc.common.ApiResponse; import cn.zhuatech.cvqc.dto.CvqcDto.*; import cn.zhuatech.cvqc.service.CvqcService; import cn.zhuatech.cvqc.service.VisualDispositionService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.Map;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/shopfloor") @PreAuthorize("hasAnyRole('DOMAIN_USER','ADMIN')") public class WorkspaceController {private final CvqcService service;private final AiProvider ai;private final VisualDispositionService disposition;/**
                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                         */
public WorkspaceController(CvqcService service,AiProvider ai,VisualDispositionService disposition){this.service=service;this.ai=ai;this.disposition=disposition;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                          */
@GetMapping("/dashboard") public ApiResponse<Dashboard> dashboard(){return ApiResponse.ok(service.shopfloorDashboard());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/work-orders/{id}/reports") public ApiResponse<ReportResult> report(@PathVariable Long id,@Valid @RequestBody ReportRequest request){return ApiResponse.ok("反馈提交成功",service.report(id,request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/ai-preview") public ApiResponse<AiProvider.AiResult> preview(@RequestBody Map<String,String> body){return ApiResponse.ok(ai.execute(body.getOrDefault("prompt",""),Map.of("mode","demo")));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/visual-disposition") public ApiResponse<VisualDispositionService.DispositionResult> decide(@Valid @RequestBody VisualDispositionService.DispositionRequest request){return ApiResponse.ok("视觉缺陷处置完成",disposition.decide(request));}}
